In [3]:
import polars as pl


df = pl.DataFrame(
    {
        "client": ["Alice", "Bob", "Charlie", "David", "Eve"],
        "montant": [1200.50, 850.75, 950.00, 1100.00, 1050.25],
        "statut": ["ok", "pending", "ok", "ok", "pending"],
    }
)


df

shape: (5, 3)
┌─────────┬─────────┬─────────┐
│ client  ┆ montant ┆ statut  │
│ ---     ┆ ---     ┆ ---     │
│ str     ┆ f64     ┆ str     │
╞═════════╪═════════╪═════════╡
│ Alice   ┆ 1200.5  ┆ ok      │
│ Bob     ┆ 850.75  ┆ pending │
│ Charlie ┆ 950.0   ┆ ok      │
│ David   ┆ 1100.0  ┆ ok      │
│ Eve     ┆ 1050.25 ┆ pending │
└─────────┴─────────┴─────────┘

In [4]:
df.head()

shape: (5, 3)
┌─────────┬─────────┬─────────┐
│ client  ┆ montant ┆ statut  │
│ ---     ┆ ---     ┆ ---     │
│ str     ┆ f64     ┆ str     │
╞═════════╪═════════╪═════════╡
│ Alice   ┆ 1200.5  ┆ ok      │
│ Bob     ┆ 850.75  ┆ pending │
│ Charlie ┆ 950.0   ┆ ok      │
│ David   ┆ 1100.0  ┆ ok      │
│ Eve     ┆ 1050.25 ┆ pending │
└─────────┴─────────┴─────────┘

In [ ]:
df.schema